spring:
  datasource:
    url: jdbc:h2:mem:pokeapi_db
    driver-class-name: org.h2.Driver
    username: bankaya
    password: challenge

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE


pokeapi:
  base-path: https://pokeapi.co/api/v2/pokemon

