spring:
  datasource:
    #connection pool
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initial-size: 20
      max-wait: 20000
      max-active: 50
      default-auto-commit: true
    #h2
    url: jdbc:h2:mem:pokeapi_db
    driver-class-name: org.h2.Driver
    username: bankaya
    password: challenge

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE


pokeapi:
  base-path: https://pokeapi.co/api/v2/pokemon